### ISSUE TITLE
Sequence passed as parameter to Sequence.merge() is not lazily evaluated

### ISSUE THREAD

**Issue by couzic** [winterbe/sequency#12]
```ts
const firstArray = [...10 items...]
const secondArray = [...1000 items...]

const firstSequence = asSequence(firstArray)
const secondSequence = asSequence(secondArray).map(expensiveComputation)

asSequence(firstArray).merge(secondSequence, it => it).take(10)
```
The above code makes the `expensiveComputation` be executed 1000 times in an eager evaluation of the `secondStream`, even though the computed result only takes input from the `firstStream`

Maybe I'm missing something and there's a better way to concatenate two sequences ?

**Comment by winterbe** [comment]
Yep the current implementation of merge is non-lazy and thus expensive in certain cases. I was in a hurry finishing my current project and this impl was fast enough for my usecase. But I bet we’ll find a better algorithm.

**Comment by couzic** [comment]
I just realized that for my simple use case, I could use `Sequence.plus()` instead which is lazy, so there's no rush for me. I'm keeping this open though :)

**Comment by winterbe** [comment]
Good. 

I thought about it and don’t see a solution to lazy evaluate the given sequence because in order to process the next element you have to search the whole given sequence. The original sequence however could eventually be evaluated lazily. 

In your example the problem could be solved in user code by calling `take(10)` on the second sequence before calling merge.

**Comment by couzic** [comment]
Right, I see that now.

From what I understand, `merge()` is kind of a shorter version of:
```ts
firstSequence.plus(secondSequence)
    .distinctBy(it => ...)
```
However, the `plus()` version being lazy, I expect to always favor it.

Also, I was thinking there should be a way to explicitly document when an operation is not completely lazy, especially since the docs explicitly mention the lazy nature of Sequences. Otherwise it's kind of misleading. I'm not sure how to do that though.

A last idea: `merge` could be implemented as `plus().distinctBy()` ?

**Comment by winterbe** [comment]
> A last idea: merge could be implemented as plus().distinctBy() ?

Not exactly. Assuming: `first.plus(second).distinctBy(key)`: Since `plus` appends all elements of `second` to the end of the `first` sequence, `distinctBy` would then abandon all elements of `second` who's `key` is already included in `first`.

`merge` however would always abandon elements from `first` if keys are equal. New values from `second` who's keys are not included in `first` will either be prepended to the start or appended to the end of the new sequence.

 I use `merge` to poll server for changes since a given timestamp. The server might return a list of elements which are either new (should be appended) or updated elements (should be replaced). 
Say you write a chat app. You poll server for messages. New messages should be appended to one side of the sequence, while modified message should be replaced in-order.

**Comment by couzic** [comment]
Thanks, I get it.

Another crazy idea, `merge` implemented as:
```ts
merge<T, S>(this: Sequence<T>, other: Sequence<T>, selector: (value: T) => S): Sequence<T> {
    return other.plus(this).distinctBy(selector)
}
```

Not sure what to do with the `prependNewValues` option...

**Comment by winterbe** [comment]
This comes very close for prependNewValues = true however the order of modified elements would not be preserved. Think again of the chat app: both new and modified messages would move to the start. The current implementation however preserves the order of existing elements.

**Comment by couzic** [comment]
OK I give up :smile:, thanks for taking the time to explain.

It's just that it really bugs me to have an operation taking in a sequence which is eagerly evaluated. I think it can be quite misleading. From a user's point of view, it is reasonable to assume that if it takes a Sequence, it must be lazy.

There should be a way to make it explicit that evaluation is not lazy. It could be as simple as accepting arrays only.

**Comment by winterbe** [comment]
As a first step we should just mention in the docs whether it's lazy or not. `sorted` and `reverse` are other operation which are not lazy.
