### ISSUE TITLE
groupBy returning sequence

### ISSUE THREAD

**Issue by Yona-Appletree** [winterbe/sequency#28]
When using `groupBy`, I often want to continue using sequence operators on the resulting map. This is currently fairly clunky in sequency:

    asSequence(
        asSequence(someData)
            .groupBy(it => it.groupId)
            .entries
    ).map(
        ([key, values]) => ...
    )

It would be awesome to have something like:

    asSequence(someData)
        .groupByAsSequence(it => it.groupId)
        .map(([key, value]) => ...)

**Comment by couzic** [comment]
@Yona-Appletree I also have felt the same need here and there, so far I have been relying on Ramda's `groupBy()`:
https://ramdajs.com/docs/#groupBy

But lately I discovered this library, `tidy`, which I feel can be pretty powerful when working with mapped structures.
https://github.com/pbeshai/tidy#grouping-data-with-groupby

**Comment by winterbe** [comment]
In order to keep the API surface clean and stick with the original Kotlin Sequence API, I don't have plans to add such method to the library. However you can use `extendSequence` to add this Sequence operation for your projects. See this example for usage:

https://github.com/winterbe/sequency/blob/ac3dbb0f212bb08783d970472c7a76dc921b60ba/test/extendSequence.test.ts
