### ISSUE TITLE
.sortedWith() to accept an array of comparators

### ISSUE THREAD

**Issue by couzic** [winterbe/sequency#5]
I have found that Ramda's `sortWith()` function is very expressive and powerful because it accepts an array of comparators:
[http://ramdajs.com/docs/#sortWith](http://ramdajs.com/docs/#sortWith)
By comparison, sequency's `sortedWith()` forces a more obscure and verbose style when sorting by multiple fields.
Moreover, if `.sortedWith()` accepted arrays of comparators, we would be able to feed it Ramda-created comparators (it's already possible to feed it a single Ramda comparator though)

**Comment by couzic** [comment]
Now that I think about it, correct me if I'm wrong but maybe we already have something pretty decent. If I'm trying to do the equivalent of the following Ramda code (copied from the docs):
```js
var alice = {
  name: 'alice',
  age: 40
};
var bob = {
  name: 'bob',
  age: 30
};
var clara = {
  name: 'clara',
  age: 40
};
var people = [clara, bob, alice];
var ageNameSort = R.sortWith([
  R.descend(R.prop('age')),
  R.ascend(R.prop('name'))
]);
ageNameSort(people); //=> [alice, clara, bob]
```
... we could do something like:
```js
asSequence(people)
  .sortedWith(R.ascend(R.prop('name')))
  .sortedWith(R.descend(R.prop('age')))
  .toArray() //=> [alice, clara, bob]
```
It is a bit counter-intuitive since the last comparator will have priority over the previous ones though. Anyway, it could be a quick way to implement the comparator array-accepting version of `.sortedWith()`. However, I'm not sure the sorting algorithm implementation used here guarantees that the previous sorting pass is unaltered.

**Comment by winterbe** [comment]
I totally agree with you that currently sequence sorting is kinda limited because there's no simple solution for combining multiple comparators. This is something I definitely want to address in a future version of Sequency.

I want something as expressive as your Ramda example but in a type-safe way which fits well into the current API design which is inspired by Kotlin. [Kotlin provides extensions](https://kotlinlang.org/api/latest/jvm/stdlib/kotlin.comparisons/java.util.-comparator/index.html) to compose and transform comparators in order to express complex sorting behavior. Let's see how this could be incorporated into Sequency.

As for your workaround: Calling `sortedWith()` twice is the equivalent of calling `sort` twice on an array, so I guess your example could work as a workaround (by flipping the order of comparators). However it's indeed not very intuitive, hard to read and non-performant on large input collections.

**Comment by couzic** [comment]
Your answer sent me looking for a Comparator building library, I found this one:
[https://github.com/spencerwi/Comparators.js](https://github.com/spencerwi/Comparators.js)
Not exactly what you had in mind but...

It could make sense to have a separate library, so it could be used everywhere, even in native JS arrays' `.sort()` method. Although ensuring type-safety might require explicit comparator typing, adding verbosity...

Anyway, I'm curious to see what you'll come up with !

**Comment by winterbe** [comment]
I agree with you that explicit comparator typing would be cumbersome and my first attempt actually didn't work quite well with type inference. However I came up with a type-safe solution which fits well into TypeScripts type inference.

Please take a look at this example and let me know what you think: 

https://github.com/winterbe/sequency/blob/a09c90c00b85d5ff6ab23775647fe033577e60b7/test/sortedWith.test.ts#L48-L59

**Comment by winterbe** [comment]
I made a few more changes: I've reverted `sortedWith()` back to the original version. Instead `sorted()` now optionally accept the `composeComparator` function. So no longer breaking changes.

Using the `composeComparator` function parameter adds a bit of noise but enables a full type-safe API with type inference. So IMO it's a good trade-off.

Here's a few examples of the new API:

https://github.com/winterbe/sequency/blob/4c6ef90bb8ec87cb88aad2dc998f887a6d01ecda/test/sorted.test.ts#L28-L100

**Comment by winterbe** [comment]
I've published v0.11.0 with comparator composition as described above. Please let me know if it fits all your usecases.

**Comment by couzic** [comment]
Thanks !

I agree with the use of `sorted()` and the optional `composeComparator` parameter, I see no better solution either. I have a remark though, but it's mostly about style and personal taste.

I'll just write how I would expect/enjoy using the API:
```ts
asSequence(people)
  // ...
  .sorted(comparing => comparing
      .by((it => it.lastName)
      .thenBy(it => it.firstName)
      .thenByDescending(it => it.age)
  )
```
So basically I'd just rename or provide an alias for `compareBy()` and `compareByDescending()`

Also here's an idea, maybe a bit drastic and probably not worth the API overhaul:
```ts
asSequence(people)
  // ...
  .sorted(({by}) => by((it => it.lastName).descending()
      .thenBy(it => it.firstName)
      .thenBy(it => it.age).descending()
  )
```
I feel this brings more consistency in the code.

But anyway great work, my use cases are covered !

**Comment by winterbe** [comment]
I like your first suggestion however I'm not a big fan of aliases because it clutters the whole API. But in this case the alias might be useful. Give me a few days to think about it.

Your second idea would be nicely readable however it won't work as expected because calling `thenBy` already returns the combined comparator. Calling `descending` on the combined comparator would flip the whole order instead of just flipping the order of the preceding`thenBy` call.

**Comment by couzic** [comment]
Agreed !
